#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 14 17:04:27 2018

@author: elishatam
"""

import matplotlib.pyplot as plt
import numpy as np

x, y = np.loadtxt('blue.txt', delimiter=' ', unpack=True)
plt.plot(x,y, label='loaded from blue.txt')

plt.xlabel('x')
plt.ylabel('y')
plt.title('Interesting graph\nCheck it out')
plt.legend()
plt.show()